import "./time.js";
import "./audio.js";
import "./asset.js";
import "./buffer.js";
import "./storage.js";
import "./camera.js";
import "./sprite.js";
import "./game.js";
import "./screen.js";
import "./quad.js"
import "./input.js";
import "./javascript.js";
import "./platform.js";
